'use client';
import Link from 'next/link';
import { useEffect,useState } from 'react';
import { ArrowLeft,ArrowUpRight,Clapperboard,Image as ImageIcon,Sparkles,Video } from 'lucide-react';
import { loadCreationDraft,type CreationDraft } from '@/lib/creative-draft';

export default function CreatePage(){
 const [draft,setDraft]=useState<CreationDraft|null>(null);
 useEffect(()=>setDraft(loadCreationDraft()),[]);
 if(!draft)return <main className="creationBridge"><Link href="/" className="bridgeBack"><ArrowLeft size={16}/> Back to conversation</Link><div className="bridgeEmpty"><Sparkles size={28}/><span>CREATION BRIDGE</span><h1>Start with a conversation.</h1><p>Choose a character, shape an idea, then bring it here to turn the conversation into an image, video or storyboard.</p><Link href="/">Open conversations <ArrowUpRight size={15}/></Link></div></main>;
 return <main className="creationBridge"><header className="bridgeHeader"><Link href="/"><ArrowLeft size={16}/> Conversation</Link><div><span>CREATION BRIDGE</span><b>MOTIONA</b></div><Link href="/gallery">Library <ArrowUpRight size={15}/></Link></header><section className="bridgeGrid"><div className="bridgeContext"><span className="bridgeEyebrow">FROM YOUR CONVERSATION</span><h1>{draft.characterName}</h1><p className="bridgePrompt">{draft.prompt}</p><div className="bridgeMessages">{draft.messages.slice(-6).map((m,i)=><div key={i} className={m.role==='user'?'bridgeMessage user':'bridgeMessage'}><b>{m.role==='user'?'You':draft.characterName}</b><p>{m.content}</p></div>)}</div></div><div className="bridgeActions"><span className="bridgeEyebrow">TAKE IT FURTHER</span><h2>One idea. Three creative paths.</h2><Link href="/studio?view=generate" className={draft.mode==='image'?'bridgeAction active':'bridgeAction'}><ImageIcon/><span><b>Create image</b><small>Carry the character and conversation into the image workspace.</small></span><ArrowUpRight/></Link><Link href="/animate" className={draft.mode==='video'?'bridgeAction active':'bridgeAction'}><Video/><span><b>Create video</b><small>Move from direction into flexible 5–60 second animation.</small></span><ArrowUpRight/></Link><Link href="/storyboard" className={draft.mode==='scene'?'bridgeAction active':'bridgeAction'}><Clapperboard/><span><b>Build storyboard</b><small>Turn the conversation into shots, continuity and camera direction.</small></span><ArrowUpRight/></Link><div className="bridgeState"><Sparkles/><div><b>Context carried forward</b><span>{draft.characterName} · {draft.mode} direction · {draft.messages.length} messages</span></div></div></div></section></main>;
}