'use client';
import { useEffect, useMemo, useState } from 'react';
import { Film, Plus, Copy, Trash2, ArrowUp, ArrowDown, LockKeyhole, Sparkles, Save, ShieldCheck } from 'lucide-react';
import type { Shot, Storyboard } from '@/lib/storyboard';
import { randomSeed } from '@/lib/storyboard';
type Props={characters:Array<{id:string;name:string;role:string;style:string;traits:string}>;selectedCharacterId?:string};
const makeShot=(index:number,characterId?:string):Shot=>({id:crypto.randomUUID(),scene:'Shot '+(index+1),duration:5,prompt:'',camera:'Medium shot',dialogue:'',characterId,status:'draft'});
export default function SceneShotWorkspace({characters,selectedCharacterId}:Props){
const [board,setBoard]=useState<Storyboard>(()=>({id:crypto.randomUUID(),title:'Untitled sequence',aspectRatio:'16:9',shots:[makeShot(0,selectedCharacterId)],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),masterSeed:randomSeed(),characterName:characters.find(c=>c.id===selectedCharacterId)?.name,worker:'ComfyUI'}));
const [activeId,setActiveId]=useState(board.shots[0].id); const [status,setStatus]=useState('Draft — nothing rendered'); const [saving,setSaving]=useState(false);
const active=useMemo(()=>board.shots.find(s=>s.id===activeId)||board.shots[0],[board,activeId]); const activeCharacter=characters.find(c=>c.id===active?.characterId);
useEffect(()=>{const id=sessionStorage.getItem('motiona-active-board');if(!id)return;fetch('/api/storyboards?id='+encodeURIComponent(id),{cache:'no-store'}).then(r=>r.ok?r.json():null).then(d=>{if(d?.storyboard?.shots?.length){setBoard(d.storyboard);setActiveId(d.storyboard.shots[0].id)}}).catch(()=>{})},[]);
function patch(p:Partial<Shot>){setBoard(b=>({...b,updatedAt:new Date().toISOString(),shots:b.shots.map(s=>s.id===active.id?{...s,...p}:s)}));setStatus('Unsaved changes')}
function add(){const s=makeShot(board.shots.length,selectedCharacterId||active?.characterId);setBoard(b=>({...b,shots:[...b.shots,s],updatedAt:new Date().toISOString()}));setActiveId(s.id);}
function duplicate(){const s={...active,id:crypto.randomUUID(),scene:active.scene+' copy',status:'draft' as const,jobId:undefined,promptId:undefined,outputs:undefined,error:undefined};setBoard(b=>{const i=b.shots.findIndex(x=>x.id===active.id),a=[...b.shots];a.splice(i+1,0,s);return {...b,shots:a,updatedAt:new Date().toISOString()}});setActiveId(s.id)}
function remove(){if(board.shots.length===1){setStatus('A sequence needs at least one shot.');return}const i=board.shots.findIndex(x=>x.id===active.id),next=board.shots[i-1]||board.shots[i+1];setBoard(b=>({...b,shots:b.shots.filter(x=>x.id!==active.id),updatedAt:new Date().toISOString()}));setActiveId(next.id)}
function move(d:number){const i=board.shots.findIndex(x=>x.id===active.id),j=i+d;if(j<0||j>=board.shots.length)return;const a=[...board.shots];[a[i],a[j]]=[a[j],a[i]];setBoard(b=>({...b,shots:a,updatedAt:new Date().toISOString()}))}
async function save(){setSaving(true);setStatus('Saving sequence…');try{const r=await fetch('/api/storyboards',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({storyboard:board})});if(!r.ok)throw new Error('Sign in is required to save a private sequence.');const d=await r.json();sessionStorage.setItem('motiona-active-board',d.storyboard.id);setBoard(d.storyboard);setStatus('Saved to your private storyboard')}catch(e){setStatus(e instanceof Error?e.message:'Could not save sequence')}finally{setSaving(false)}}
return <section className='sceneStudio'><div className='sceneHeader'><div><p className='eyebrow'><Film size={14}/> SCENE / SHOT WORKSPACE · 18+ CREATIVE</p><h1>Direct the sequence.</h1><p>Build adult-oriented fictional scenes as a sequence of shots. Character continuity, camera language and timing stay attached to each shot.</p></div><div className='sceneHeaderActions'><label>Sequence title<input value={board.title} onChange={e=>setBoard(b=>({...b,title:e.target.value,updatedAt:new Date().toISOString()}))}/></label><button className='secondary' onClick={save} disabled={saving}><Save size={15}/>{saving?'Saving…':'Save private sequence'}</button></div></div>
<div className='sceneShell'><aside className='shotRail'><div className='railHead'><span>{board.shots.length} SHOTS</span><button className='secondary iconBtn' onClick={add}><Plus size={15}/></button></div><div className='shotList'>{board.shots.map((s,i)=><button key={s.id} className={s.id===active.id?'shotThumb active':'shotThumb'} onClick={()=>setActiveId(s.id)}><span>{String(i+1).padStart(2,'0')}</span><b>{s.scene}</b><small>{s.duration}s · {s.camera}</small></button>)}</div><div className='railTools'><button onClick={()=>move(-1)}><ArrowUp size={14}/> Move up</button><button onClick={()=>move(1)}><ArrowDown size={14}/> Move down</button><button onClick={duplicate}><Copy size={14}/> Duplicate</button><button onClick={remove}><Trash2 size={14}/> Delete</button></div></aside>
<main className='shotCanvas'><div className='frameStage'><div className='frameGrid'/><div className='frameEmpty'><Film size={28}/><strong>FRAME NOT GENERATED</strong><span>Use the configured ComfyUI workflow when this shot is ready. No placeholder render is presented as a real output.</span></div><div className='frameMeta'><span>SHOT {String(board.shots.findIndex(s=>s.id===active.id)+1).padStart(2,'0')}</span><span>{board.aspectRatio}</span><span>{active.duration}s</span></div></div><div className='shotPrompt'><label>SHOT DIRECTION<textarea value={active.prompt} onChange={e=>patch({prompt:e.target.value})} placeholder='Describe composition, environment, adult characters, action, wardrobe, lighting and emotional tone.'/></label></div></main>
<aside className='shotInspector'><div className='inspectorBlock'><b>CONTINUITY LOCK</b><div className='lockCard'><LockKeyhole size={16}/><div><strong>{activeCharacter?.name||board.characterName||'No character locked'}</strong><span>{activeCharacter?.traits||'Select an adult character for continuity.'}</span></div></div><button className='secondary full' onClick={()=>patch({characterId:selectedCharacterId})}>Lock selected character</button></div><div className='inspectorBlock'><b>SHOT PARAMETERS</b><label>Shot name<input value={active.scene} onChange={e=>patch({scene:e.target.value})}/></label><label>Duration<input type='number' min='1' max='60' value={active.duration} onChange={e=>patch({duration:Number(e.target.value)||1})}/></label><label>Camera<select value={active.camera} onChange={e=>patch({camera:e.target.value})}>{['Wide shot','Medium shot','Close-up','Tracking shot','POV'].map(x=><option key={x}>{x}</option>)}</select></label><label>Dialogue / VO<textarea value={active.dialogue} onChange={e=>patch({dialogue:e.target.value})} placeholder='Optional dialogue or voice direction'/></label><label>Continuity seed<input type='number' value={active.seed??board.masterSeed??''} onChange={e=>patch({seed:Number(e.target.value)||undefined})}/></label></div><div className='safetyCard'><ShieldCheck size={17}/><div><b>18+ / CONSENT LOCK</b><p>Fictional adults only. No minors, non-consensual sexual scenarios, or sexualized real-person likenesses.</p></div></div><div className='inspectorActions'><button className='primary full' onClick={()=>setStatus('Shot prepared for the configured render workflow.')}><Sparkles size={15}/> Prepare render</button><span>{status}</span></div></aside></div></section>}